name = "Kancelaria Notarialna Anna Grygowicz-Haberek Notariusz"
license = "MIT"
description = "Kancelaria Notarialna Anna Grygowicz-Haberek Notariusz"
homepage = "http://www.notariuszwrzeszowie.pl"
tags = ['notariusz rzeszów', 'tani notariusz rzeszów', 'notariusz w sobotę rzeszów', 'notariusz w rzeszowie', 'kancelaria notarialna w rzeszowie', 'notariusze rzeszów', 'kancelarie notarialne Rzeszów', 'notariusz Rzeszów centrum', 'notariusz Rzeszów Kopernika', 'notariusz Rzeszów Matejki', 'akt notarialny', 'akty notarialne', 'notariusz Anna Grygowicz-Haberek', 'notariusz na parterze', 'notariusz blisko starostwa', 'notariusz blisko geodezji']
features = ['bootstrap','responsive']
min_version = "0.58.0"
