baseURL = "https://whaberek.netlify.app"
# baseURL = "https://notariuszwrzeszowie.pl"
languageCode = "pl-PL"
summaryLength = "10"
theme = "notariuszwrzeszowie"
title = "Kancelaria Notarialna Anna Grygowicz-Haberek Notariusz, Rzeszów"
enableRobotsTXT = "true"

# css plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"


# menu
[[menu.main]]
URL = "o-kancelarii"
name = "O kancelarii"
weight = 2
[[menu.main]]
URL = "czynnosci"
name = "Czynności"
weight = 3
[[menu.main]]
URL = "dokumenty"
name = "Dokumenty"
weight = 4
[[menu.main]]
URL = "przydatne"
name = "Przydatne linki"
weight = 5
[[menu.main]]
URL = "oplaty"
name = "Opłaty"
weight = 6
[[menu.main]]
URL = "kontakt"
name = "Kontakt"
weight = 7
[params]
address = "ul. 3 Maja<br>35-604 Rzeszów"
author = "Wojciech Haberek"
copyright = "Copyrighht &copy; 2020 a theme by [Wojciech Haberek](http://whaberek.pl)"
description = "Kancelaria Notarialna Anna Grygowicz-Haberek, Rzeszów, podkarpackie, Anna Grygowicz, kom. +48 506 550 710, email: kancelaria@notariuszwrzeszowie.pl - Zapraszamy do współpracy - skontaktuj się z nami!"
email = "kancelaria@notariuszwrzeszowie.pl"
google_analitycs_id = "UA-15183956-5"
home = "Strona Główna"
logo = "images/emblem.png"
phone = "+48 500 500 500"
theme_color = "#41228e"
[params.contact]
enable = true
form_action = "#"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/fontawesome-icons/css/all.min.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = false
preloader = "/images/progress-wave.png"
[[params.social]]
URL = "#"
icon = "fa-facebook-f"